name:ğŸ”¥â¤ï¸ğŸ˜è‹—å¾—é›¨çš„ç§å¯†ç©ºé—´ğŸ˜ğŸ”¥åŠ²ï¼ï¼ï¼
url: https://miaodeyu.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: faculty
    name: æ•™å¸ˆ Faculty
  - key: grad
    name: ç ”ç©¶ç”Ÿ Graduate Students
  - key: ugrad
    name: æœ¬ç§‘ç”Ÿ Undergraduate Students
  - key: collab
    name: åˆä½œè€… Collaborators


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: ä¸»é¡µ Home
    link: /
  - title: ç§‘ç ” Research
    link: /research.html
  - title: è®ºæ–‡ Publications
    link: /publications.html
